### ISSUE TITLE
Getting errors with turning on the datastax/dse-opscenter image

### ISSUE THREAD

**Issue by holajoyce** [datastax/docker-images#38]
just following the instructions on the page, but getting errors like:
`Starting OpsCenter with -f
Detected Java version 1.8.0
2018-08-22 18:24:56,582 [opscenterd] INFO: Loading OpsCenter...
2018-08-22 18:24:56,595 [opscenterd] INFO: Updating system path
2018-08-22 18:24:56,601 [opscenterd] INFO: Importing twisted logging
2018-08-22 18:25:04,191 [opscenterd] INFO: Finished importing twisted logging
2018-08-22 18:25:04,194 [opscenterd] INFO: Opscenterd starting up...
/opt/opscenter/lib/py/twisted/python/modules.py:792: UserWarning: /opt/opscenter/lib/py (for module twisted.plugins) not in path importer cache (PEP 302 violation - check your local configuration).
  return theSystemPath[moduleName]
Unhandled Error
Traceback (most recent call last):
  File "/opt/opscenter/lib/py/twisted/python/usage.py", line 411, in <lambda>
    fn = lambda name, value, m=method: m(value)
  File "/opt/opscenter/lib/py/twisted/application/app.py", line 486, in opt_reactor
    installReactor(shortName)
  File "/opt/opscenter/lib/py/twisted/application/reactors.py", line 80, in installReactor
    for installer in getReactorTypes():
  File "/opt/opscenter/lib/py/twisted/plugin.py", line 213, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/opt/opscenter/lib/py/twisted/plugin.py", line 171, in getCache
    provider = pluginModule.load()
  File "/opt/opscenter/lib/py/twisted/python/modules.py", line 394, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/opt/opscenter/lib/py/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/opt/opscenter/lib/py/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/opt/opscenter/lib/py/twisted/python/reflect.py", line 242, in _importAndCheckStack
    return __import__(importName)
  File "/opt/opscenter/lib/py/twisted/python/reflect.py", line 242, in _importAndCheckStack
    return __import__(importName)
  File "/opt/opscenter/lib/py/twisted/plugins/cred_sshkeys.py", line 23, in <module>
    from twisted.conch.checkers import (
  File "/opt/opscenter/lib/py/twisted/plugins/cred_sshkeys.py", line 23, in <module>
    from twisted.conch.checkers import (
  File "/opt/opscenter/lib/py/twisted/conch/checkers.py", line 15, in <module>
    import crypt
  File "/opt/opscenter/lib/jvm/jython-standalone-2.7.0.11.jar/Lib/crypt.py", line 6, in <module>

exceptions.TypeError: getPOSIX(): 1st arg can't be coerced to jnr.posix.POSIXHandler

2018-08-22 18:25:09,957 [opscenterd] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "/opt/opscenter/lib/py/twisted/python/usage.py", line 411, in <lambda>
    fn = lambda name, value, m=method: m(value)
  File "/opt/opscenter/lib/py/twisted/application/app.py", line 486, in opt_reactor
    installReactor(shortName)
  File "/opt/opscenter/lib/py/twisted/application/reactors.py", line 80, in installReactor
    for installer in getReactorTypes():
  File "/opt/opscenter/lib/py/twisted/plugin.py", line 213, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/opt/opscenter/lib/py/twisted/plugin.py", line 171, in getCache
    provider = pluginModule.load()
  File "/opt/opscenter/lib/py/twisted/python/modules.py", line 394, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/opt/opscenter/lib/py/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/opt/opscenter/lib/py/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/opt/opscenter/lib/py/twisted/python/reflect.py", line 242, in _importAndCheckStack
    return __import__(importName)
  File "/opt/opscenter/lib/py/twisted/python/reflect.py", line 242, in _importAndCheckStack
    return __import__(importName)
  File "/opt/opscenter/lib/py/twisted/plugins/cred_sshkeys.py", line 23, in <module>
    from twisted.conch.checkers import (
  File "/opt/opscenter/lib/py/twisted/plugins/cred_sshkeys.py", line 23, in <module>
    from twisted.conch.checkers import (
  File "/opt/opscenter/lib/py/twisted/conch/checkers.py", line 15, in <module>
    import crypt
  File "/opt/opscenter/lib/jvm/jython-standalone-2.7.0.11.jar/Lib/crypt.py", line 6, in <module>

exceptions.TypeError: getPOSIX(): 1st arg can't be coerced to jnr.posix.POSIXHandler

2018-08-22 18:25:16,151 [opscenterd] INFO: Loading bin/start_opscenter.py...
/opt/opscenter/lib/py/twisted/python/modules.py:792: UserWarning: /opt/opscenter/lib/py (for module twisted.web.util) not in path importer cache (PEP 302 violation - check your local configuration).
  return theSystemPath[moduleName]
2018-08-22 18:25:26,338 [opscenterd] INFO: OpsCenter initial startup process complete. End logging to startup.log`

**Comment by bschoeni** [comment]
I'm seeing the same error when installing OpsCenter 6.5.3 as a RPM package and

**Comment by MelissaPang** [comment]
I got the same error. Is there a solution yet?
