### ISSUE TITLE
DSE Server volume mounts not working with search enabled

### ISSUE THREAD

**Issue by AndyNorris** [datastax/docker-images#54]
I am trying to use the combination of Docker DSE Server with persisted volumes and search enabled on Docker for Windows with DSE 6. Volume mounts are working fine for creating namespaces tables and data, it is only when I run the command CREATE SEARCH INDEX ON videodb.videos; I get a failure.

Without volume mounts I am able to create and use SOLR indexes, but with I get the failure:

An error occurred on line 1: 
Failed to create search index videodb.videos because: Error opening new searcher: no segments* file found in LockValidatingDirectoryWrapper(MMapDirectory@/var/lib/cassandra/data/solr.data/videodb.videos/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@39e85a71): files: [write.lock]

in DSE Studio.

My docker run command is 
docker run -e DS_LICENSE=accept --link my-opscenter:opscenter --name my-dse -v C:/dsepersist/data:/var/lib/cassandra -v C:/dsepersist/spark:/var/lib/spark -v C:/dsepersist/dsefs:/var/lib/dsefs -v C:/dsepersist/logs:/var/log/cassandra -v C:/dsepersist/sparklogs:/var/log/spark -v C:/dsepersist/config:/config -d -p 9042:9042 datastax/dse-server -s 

the error is the DSE log is:
ERROR [IOThread-0] 2018-11-21 11:01:06,490  SolrIndexWriter.java:147 - Error closing IndexWriter
java.lang.AssertionError: On Linux and MacOSX fsyncing a directory should not throw IOException, we just don't want to rely on that in production (undocumented). Got: java.io.IOException: Invalid argument
        at org.apache.lucene.util.IOUtils.fsync(IOUtils.java:423)
        at org.apache.lucene.store.FSDirectory.renameFile(FSDirectory.java:303)
        at org.apache.lucene.store.LockValidatingDirectoryWrapper.renameFile(LockValidatingDirectoryWrapper.java:56)
        at org.apache.lucene.index.SegmentInfos.finishCommit(SegmentInfos.java:826)
        at org.apache.lucene.index.IndexWriter.finishCommit(IndexWriter.java:3321)
        at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3285)
        at org.apache.lucene.index.IndexWriter.shutdown(IndexWriter.java:1227)
        at org.apache.lucene.index.IndexWriter.close(IndexWriter.java:1281)
        at org.apache.solr.update.SolrIndexWriter.close(SolrIndexWriter.java:142)
        at org.apache.solr.update.SolrIndexWriter.close(SolrIndexWriter.java:135)
        at org.apache.solr.core.SolrCore.initIndex(SolrCore.java:590)
        at org.apache.solr.core.SolrCore.<init>(SolrCore.java:812)
        at com.datastax.bdp.search.solr.core.CassandraCoreContainer.doCreate(CassandraCoreContainer.java:906)
        at com.datastax.bdp.search.solr.core.CassandraCoreContainer.create(CassandraCoreContainer.java:347)
        at com.datastax.bdp.search.solr.core.SolrCoreResourceManager.createCore(SolrCoreResourceManager.java:328)
        at com.datastax.bdp.cassandra.cql3.statements.CreateSearchIndexStatement.execute(CreateSearchIndexStatement.java:172)
        at org.apache.cassandra.cql3.QueryProcessor.lambda$processStatement$4(QueryProcessor.java:262)
        at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:36)
        at io.reactivex.Single.subscribe(Single.java:2700)
        at org.apache.cassandra.utils.flow.RxThreads$1SubscribeOn.lambda$subscribeActual$0(RxThreads.java:50)
        at org.apache.cassandra.concurrent.TPCRunnable.run(TPCRunnable.java:68)
        at org.apache.cassandra.concurrent.IOScheduler$PooledTaskWorker.run(IOScheduler.java:316)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
INFO  [IOThread-0] 2018-11-21 11:01:07,034  XMLLoader.java:114 - xsltCacheLifetimeSeconds=60
INFO  [IOThread-0] 2018-11-21 11:01:07,039  PluginBag.java:118 - requestHandler : '/update/json' created with startup=lazy
INFO  [IOThread-0] 2018-11-21 11:01:07,044  PluginBag.java:118 - requestHandler : '/update/csv' created with startup=lazy
INFO  [IOThread-0] 2018-11-21 11:01:07,048  XMLLoader.java:114 - xsltCacheLifetimeSeconds=60
INFO  [IOThread-0] 2018-11-21 11:01:07,535  PluginBag.java:118 - requestHandler : '/analysis/field' created with startup=lazy
INFO  [IOThread-0] 2018-11-21 11:01:07,537  PluginBag.java:118 - requestHandler : '/analysis/document' created with startup=lazy
WARN  [IOThread-0] 2018-11-21 11:01:07,546  SolrResourceLoader.java:552 - Solr loaded a deprecated plugin/analysis class [solr.admin.AdminHandlers]. Please consult documentation how to replace it accordingly.
INFO  [searcherExecutor-4-thread-1] 2018-11-21 11:01:07,562  JmxMonitoredMap.java:123 - JMX monitoring is enabled. Adding Solr mbeans to JMX Server: com.sun.jmx.mbeanserver.JmxMBeanServer@6385cb26
INFO  [IOThread-0] 2018-11-21 11:01:07,666  CachingDirectoryFactory.java:237 - looking to close /var/lib/cassandra/data/solr.data/videodb.videos/index [CachedDir<<refCount=0;path=/var/lib/cassandra/data/solr.data/videodb.videos/index;done=true>>]
INFO  [IOThread-0] 2018-11-21 11:01:07,667  CachingDirectoryFactory.java:306 - Closing directory: /var/lib/cassandra/data/solr.data/videodb.videos/index
INFO  [IOThread-0] 2018-11-21 11:01:07,692  CachingDirectoryFactory.java:169 - Closing StandardDirectoryFactory - 1 directories currently being tracked
INFO  [IOThread-0] 2018-11-21 11:01:07,694  CachingDirectoryFactory.java:237 - looking to close /var/lib/cassandra/data/solr.data/videodb.videos [CachedDir<<refCount=0;path=/var/lib/cassandra/data/solr.data/videodb.videos;done=false>>]
INFO  [IOThread-0] 2018-11-21 11:01:07,695  CachingDirectoryFactory.java:306 - Closing directory: /var/lib/cassandra/data/solr.data/videodb.videos
ERROR [IOThread-0] 2018-11-21 11:01:07,695  CassandraCoreContainer.java:369 - Error opening new searcher
org.apache.solr.common.SolrException: Error opening new searcher
        at org.apache.solr.core.SolrCore.<init>(SolrCore.java:879)
        at com.datastax.bdp.search.solr.core.CassandraCoreContainer.doCreate(CassandraCoreContainer.java:906)
        at com.datastax.bdp.search.solr.core.CassandraCoreContainer.create(CassandraCoreContainer.java:347)
        at com.datastax.bdp.search.solr.core.SolrCoreResourceManager.createCore(SolrCoreResourceManager.java:328)
        at com.datastax.bdp.cassandra.cql3.statements.CreateSearchIndexStatement.execute(CreateSearchIndexStatement.java:172)
        at org.apache.cassandra.cql3.QueryProcessor.lambda$processStatement$4(QueryProcessor.java:262)
        at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:36)
        at io.reactivex.Single.subscribe(Single.java:2700)
        at org.apache.cassandra.utils.flow.RxThreads$1SubscribeOn.lambda$subscribeActual$0(RxThreads.java:50)
        at org.apache.cassandra.concurrent.TPCRunnable.run(TPCRunnable.java:68)
        at org.apache.cassandra.concurrent.IOScheduler$PooledTaskWorker.run(IOScheduler.java:316)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.common.SolrException: Error opening new searcher
        at org.apache.solr.core.SolrCore.openNewSearcher(SolrCore.java:1779)
        at org.apache.solr.core.SolrCore.getSearcher(SolrCore.java:1890)
        at org.apache.solr.core.SolrCore.initSearcher(SolrCore.java:974)
        at org.apache.solr.core.SolrCore.<init>(SolrCore.java:846)
        ... 18 common frames omitted
Caused by: org.apache.lucene.index.IndexNotFoundException: no segments* file found in LockValidatingDirectoryWrapper(MMapDirectory@/var/lib/cassandra/data/solr.data/videodb.videos/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@39e85a71): files: [write.lock]
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1033)
        at org.apache.solr.update.SolrIndexWriter.<init>(SolrIndexWriter.java:81)
        at org.apache.solr.update.SolrIndexWriter.create(SolrIndexWriter.java:67)
        at org.apache.solr.update.DefaultSolrCoreState.createMainIndexWriter(DefaultSolrCoreState.java:233)
        at org.apache.solr.update.DefaultSolrCoreState.getIndexWriter(DefaultSolrCoreState.java:113)
        at org.apache.solr.core.SolrCore.openNewSearcher(SolrCore.java:1740)
        ... 21 common frames omitted
ERROR [IOThread-0] 2018-11-21 11:01:07,711  SolrCoreResourceManager.java:354 - Error opening new searcher
org.apache.solr.common.SolrException: Error opening new searcher
        at org.apache.solr.core.SolrCore.<init>(SolrCore.java:879)
        at com.datastax.bdp.search.solr.core.CassandraCoreContainer.doCreate(CassandraCoreContainer.java:906)
        at com.datastax.bdp.search.solr.core.CassandraCoreContainer.create(CassandraCoreContainer.java:347)
        at com.datastax.bdp.search.solr.core.SolrCoreResourceManager.createCore(SolrCoreResourceManager.java:328)
        at com.datastax.bdp.cassandra.cql3.statements.CreateSearchIndexStatement.execute(CreateSearchIndexStatement.java:172)
        at org.apache.cassandra.cql3.QueryProcessor.lambda$processStatement$4(QueryProcessor.java:262)
        at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:36)
        at io.reactivex.Single.subscribe(Single.java:2700)
        at org.apache.cassandra.utils.flow.RxThreads$1SubscribeOn.lambda$subscribeActual$0(RxThreads.java:50)
        at org.apache.cassandra.concurrent.TPCRunnable.run(TPCRunnable.java:68)
        at org.apache.cassandra.concurrent.IOScheduler$PooledTaskWorker.run(IOScheduler.java:316)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.common.SolrException: Error opening new searcher
        at org.apache.solr.core.SolrCore.openNewSearcher(SolrCore.java:1779)
        at org.apache.solr.core.SolrCore.getSearcher(SolrCore.java:1890)
        at org.apache.solr.core.SolrCore.initSearcher(SolrCore.java:974)
        at org.apache.solr.core.SolrCore.<init>(SolrCore.java:846)
        ... 18 common frames omitted
Caused by: org.apache.lucene.index.IndexNotFoundException: no segments* file found in LockValidatingDirectoryWrapper(MMapDirectory@/var/lib/cassandra/data/solr.data/videodb.videos/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@39e85a71): files: [write.lock]
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1033)
        at org.apache.solr.update.SolrIndexWriter.<init>(SolrIndexWriter.java:81)
        at org.apache.solr.update.SolrIndexWriter.create(SolrIndexWriter.java:67)
        at org.apache.solr.update.DefaultSolrCoreState.createMainIndexWriter(DefaultSolrCoreState.java:233)
        at org.apache.solr.update.DefaultSolrCoreState.getIndexWriter(DefaultSolrCoreState.java:113)
        at org.apache.solr.core.SolrCore.openNewSearcher(SolrCore.java:1740)

**Comment by roberd13** [comment]
@AndyNorris Windows does not support fsync and it uses SMB/CIFS protocols for volumes which prevents locking.  If you are going to run it on windows, you would need to mount on the MobyVM.  See for more info under the section `VOLUME MOUNTS FROM HOST PATHS USE A NOBRL OPTION TO OVERRIDE DATABASE LOCKING`

https://docs.docker.com/docker-for-windows/troubleshoot/#volumes

**Comment by AndyNorris** [comment]
I have managed to work around the issue stated by @roberd13 and with help with Richard Henderson in the uk by using named volume mounts, so the docker run command below allowed me to run with the Cassandra data volume persisted.

docker run -e DS_LICENSE=accept --link my-opscenter:opscenter --name my-dse --mount source=dsepersist,target=/var/lib/cassandra -p 9042:9042 datastax/dse-server -s 

more details on this approach at https://docs.docker.com/storage/volumes/
