### ISSUE TITLE
custom docker image 5.0.13 on GKE failing with below error

### ISSUE THREAD

**Issue by sangeethdba** [datastax/docker-images#61]
ERROR 03:51:13,587  DseModule.java:103 - Unable to start server. Exiting...
org.apache.cassandra.exceptions.ConfigurationException: commitlog directory '/var/lib/cassandra/commitlog' or, if it does not already exist, an existing parent directory of it, is not readable and writable for the DSE. Check file system and configuration.
	at org.apache.cassandra.config.DatabaseDescriptor.resolveAndCheckDirectory(DatabaseDescriptor.java:801) ~[cassandra-all-3.0.15.2128.jar:3.0.15.2128]
	at org.apache.cassandra.config.DatabaseDescriptor.applyConfig(DatabaseDescriptor.java:538) ~[cassandra-all-3.0.15.2128.jar:3.0.15.2128]
	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:131) ~[cassandra-all-3.0.15.2128.jar:3.0.15.2128]
	at com.datastax.bdp.config.DseConfig.isLdapAuthEnabled(DseConfig.java:552) ~[dse-core-5.0.13.jar:5.0.13]
	at com.datastax.bdp.config.DseConfig.init(DseConfig.java:402) ~[dse-core-5.0.13.jar:5.0.13]
	at com.datastax.bdp.DseCoreModule.<init>(DseCoreModule.java:76) ~[dse-core-5.0.13.jar:5.0.13]
	at com.datastax.bdp.DseModule.getRequiredModules(DseModule.java:139) ~[dse-core-5.0.13.jar:5.0.13]
	at com.datastax.bdp.server.AbstractDseModule.configure(AbstractDseModule.java:27) ~[dse-core-5.0.13.jar:5.0.13]
	at com.datastax.bdp.DseModule.configure(DseModule.java:76) ~[dse-core-5.0.13.jar:5.0.13]
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.0.jar:na]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.0.jar:na]
	at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) ~[guice-4.0.jar:na]
	at com.google.inject.Guice.createInjector(Guice.java:96) ~[guice-4.0.jar:na]

not sure why the mount is not wokring in GKE PVC

**Comment by roberd13** [comment]
@sangeethdba Were you able to get this working?  That is most likely a permissions issue for your mount.  If you change the permissions for the mount directory to 777 does it start.
